# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c863672661594d3bdcccdcd2416b1e4d"
name = "Deposit & Multipacks"
handle = "deposit-and-multipacks"
application_url = "https://britney-proposition-can-friends.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "andre-app-dev-2.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://britney-proposition-can-friends.trycloudflare.com/auth/callback",
  "https://britney-proposition-can-friends.trycloudflare.com/auth/shopify/callback",
  "https://britney-proposition-can-friends.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
