# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dd6023d5d2c99081511bd0fd2232b90c"
name = "app-template"
handle = "app-template-18"
application_url = "https://soc-msgid-veterinary-bedroom.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "andre-app-dev-2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://soc-msgid-veterinary-bedroom.trycloudflare.com/auth/callback",
  "https://soc-msgid-veterinary-bedroom.trycloudflare.com/auth/shopify/callback",
  "https://soc-msgid-veterinary-bedroom.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
