# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6430bf1d685388240be4535e7ec817eb"
name = "Zerolabs Deposit & Multipacks"
handle = "zerolabs-deposit-multipacks"
application_url = "https://zerolabs-deposit.bs2.beeclever-apps.de"
embedded = true

[build]
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://zerolabs-deposit.bs2.beeclever-apps.de/auth/callback",
  "https://zerolabs-deposit.bs2.beeclever-apps.de/auth/shopify/callback",
  "https://zerolabs-deposit.bs2.beeclever-apps.de/api/auth/callback"
]


[webhooks]
api_version = "2024-07"

[pos]
embedded = false
